"""update heritage-table column

Revision ID: 69e448c68704
Revises: 5434877d0668
Create Date: 2026-01-07 05:20:18.542454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69e448c68704'
down_revision: Union[str, None] = '5434877d0668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('world_heritages', sa.Column('spot1_title', sa.String(), nullable=True))
    op.add_column('world_heritages', sa.Column('spot1_detail', sa.String(), nullable=True))
    op.add_column('world_heritages', sa.Column('spot2_title', sa.String(), nullable=True))
    op.add_column('world_heritages', sa.Column('spot2_detail', sa.String(), nullable=True))
    op.add_column('world_heritages', sa.Column('spot3_title', sa.String(), nullable=True))
    op.add_column('world_heritages', sa.Column('spot3_detail', sa.String(), nullable=True))
    op.add_column('world_heritages', sa.Column('sites', sa.String(), nullable=True))
    op.add_column('world_heritages', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('world_heritages', 'image_url')
    op.drop_column('world_heritages', 'sites')
    op.drop_column('world_heritages', 'spot3_detail')
    op.drop_column('world_heritages', 'spot3_title')
    op.drop_column('world_heritages', 'spot2_detail')
    op.drop_column('world_heritages', 'spot2_title')
    op.drop_column('world_heritages', 'spot1_detail')
    op.drop_column('world_heritages', 'spot1_title')
    # ### end Alembic commands ###
