"""create visits table

Revision ID: a470392a7df4
Revises: b8cbf2a5cd26
Create Date: 2026-01-03 10:22:25.292356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a470392a7df4'
down_revision: Union[str, None] = '6362386c99d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firebase_uid', sa.String(), nullable=False),
    sa.Column('world_heritage_id', sa.Integer(), nullable=False),
    sa.Column('visited_from', sa.Date(), nullable=True),
    sa.Column('visited_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(visited_from IS NULL OR visited_to IS NULL) OR (visited_from <= visited_to)', name='ck_visits_date_range'),
    sa.ForeignKeyConstraint(['world_heritage_id'], ['world_heritages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firebase_uid', 'world_heritage_id', name='uq_visits_user_heritage')
    )
    op.create_index(op.f('ix_visits_firebase_uid'), 'visits', ['firebase_uid'], unique=False)
    op.create_index(op.f('ix_visits_id'), 'visits', ['id'], unique=False)
    op.create_index(op.f('ix_visits_world_heritage_id'), 'visits', ['world_heritage_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_world_heritage_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_firebase_uid'), table_name='visits')
    op.drop_table('visits')
    # ### end Alembic commands ###
