"""add badge_image_url to world_heritages

Revision ID: b8cbf2a5cd26
Revises: 9a95db445210
Create Date: 2026-01-02 05:35:05.442637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8cbf2a5cd26'
down_revision: Union[str, None] = '9a95db445210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('world_heritages', sa.Column('badge_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('world_heritages', 'badge_image_url')
    # ### end Alembic commands ###
