"""add like_count to diaries

Revision ID: fad32cae07e1
Revises: c1edd2e7f87b
Create Date: 2026-01-11 04:16:56.776708

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fad32cae07e1"
down_revision: Union[str, None] = "c1edd2e7f87b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "diaries",
        sa.Column("like_count", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("diaries", "like_count")
    # ### end Alembic commands ###
